Allow passing CPP parameters right after the filenames.
Signed-off-by: Michael Buesch <mb@bu3sch.de>

diff --git a/assembler/b43-asm b/assembler/b43-asm
--- a/assembler/b43-asm
+++ b/assembler/b43-asm
@@ -41,11 +41,25 @@ shift
 outfile="$1"
 shift
 
+cpp_args=
+if [ "$1" == "--cpp-args" ]; then
+	shift
+	while [ "$1" != "--" ]; do
+		if [ $# -eq 0 ]; then
+			echo "ERROR: --cpp-args must be terminated by --"
+			exit 4
+		fi
+		cpp_args="$cpp_args $1"
+		shift
+	done
+	shift
+fi
+
 if [ "$infile" != "-" ]; then
 	if ! [ -r "$infile" ]; then
 		echo "ERROR: Can not read input file \"$infile\""
-		exit 4
+		exit 5
 	fi
 fi
 
-$CPP -x c++ -traditional-cpp "$infile" | $B43_ASM "-" "$outfile" --__real_infile "$infile" $@
+$CPP -x c++ -traditional-cpp $cpp_args "$infile" | $B43_ASM "-" "$outfile" --__real_infile "$infile" $@
